### ISSUE TITLE
Ember is holding onto state_transition, loading start/hello instead of home

### ISSUE THREAD

**Issue by rileytaylor** [code-corps/code-corps-ember#445] opened 2016-09-18 21:32 UTC
# Problem

Navigating to the homepage often becomes impossible since `state_transition` is being held onto and set for /start/hello. Ember is holding onto it and attempting to send it to the api, resulting in the following 422 error:

{"errors":[{"status":422,"source":{"pointer":"data/attributes/state_transition"},"id":"VALIDATION_ERROR","detail":"invalid transition select_skills from selected_skills"}]}`

This can be fixed by refreshing the page and hitting save, but regardless, the `state_transition` just shouldn't remain on the server.

**Comment by JoshSmith** [comment] 2016-09-18 21:33
@rileytaylor to clarify that last bit, it's because Ember is holding onto the value of `state_transition`. The server has no concept of a transition from `selected_skills` for the transition `select_skills`.

**Comment by JoshSmith** [comment] 2016-09-27 19:05
May be resolved by #484. Will verify once merged.

**Comment by JoshSmith** [comment] 2016-09-27 19:21
This is not solved by that. Thinking that we may want to either remove it explicitly on the Ember side after a successful save, or emit a `state_transition` value from the server.

**Comment by begedin** [comment] 2016-09-28 19:54
We already have a few adapter overrides (good example is the posts adapter), which cleanup attributes and only allow certain ones to go to the server. We could do the same with state transitions.

**Comment by JoshSmith** [comment] 2016-09-28 19:55
@begedin do you think the server approach is a bad idea? The server should _always_ tell the client that "hey, you're not transitioning anymore" IMO.

**Comment by begedin** [comment] 2016-09-28 19:57
We could modify the server changeset as well, true. But then the server is basically taking care of client behavior. It's conceivable that some other hypothetical client might need to behave differently. The server should care if the PATCH/PUT requested by the client is valid or not. To client should ensure the PATCH/PUT they send is valid if it wants the server to accept it.

I see arguments for both sides, though.

**Comment by JoshSmith** [comment] 2016-09-28 19:58
@begedin not talking about changing the changeset. It's still a virtual field on the `User`. Instead we just render `state_transition` in the `UserView`, which would _always_ be `nil`.

**Comment by begedin** [comment] 2016-09-28 20:00
Then the client will receive a nil and try to send that back, which the server again won't accept, no? As far as I understand, the problem is that the client is sending a value for state transition, which the server considers invalid.

**Comment by JoshSmith** [comment] 2016-09-28 20:02
I'm not sure why the client would try to send back a new value if it hasn't changed from what the server expects. Does Ember send _every_ value?

**Comment by JoshSmith** [comment] 2016-09-28 20:08
I've tested it. Setting `state_transition` to `nil` will cause no error on Phoenix.

**Comment by JoshSmith** [comment] 2016-09-28 20:09
That's because we have this clause `nil -> changeset`.

**Comment by JoshSmith** [comment] 2016-09-28 20:09
In other words, we're already prepared to handle this change, we just need to render that `nil` value back out again. And this works magically with virtual attributes.

**Comment by begedin** [comment] 2016-09-28 21:56
Then it's the simplest solution. I'm ok with resolving it API-side in that case.

**Comment by JoshSmith** [comment] 2016-09-28 21:56
👍  That's my feeling. Simpler is better.

**Closed** 2016-09-28 22:01 UTC
Labels: bug, hacktoberfest, help wanted, high priority
