### ISSUE TITLE
Sign up occasionally complains about invalid email

### ISSUE THREAD

**Issue by hbrysiewicz** [code-corps/code-corps-ember#228] opened 2016-06-20 18:54 UTC
Have not been able to reproduce but somehow got into a state where everything looked good except form complained my email was not valid. 

![screen shot 2016-06-20 at 11 46 10 am](https://cloud.githubusercontent.com/assets/2779962/16206507/94e2d75a-36dd-11e6-9bc3-5ff8ae56d333.png)

After reloading and trying again, it worked. I selected my email out of autocomplete in Chrome so it may be related to that? Not sure how the events to validate with server are getting triggered but perchance it is happening when autocomplete is selected and I move on to next field without triggering said event.

**Comment by JoshSmith** [comment] 2016-06-20 18:56
Thanks, we'll need to figure out a way to reproduce consistently and put it into a regression test. This is a definite bug.

**Comment by JoshSmith** [comment] 2016-09-28 18:34
Closing because unverified.

**Closed by JoshSmith** 2016-09-28 18:34 UTC
Labels: bug, good for new contributors, low priority, needs bug verification
